#pragma once
#include <vector>
#include <functional>
#include <string>
#include <cstdio>
#include <cstdint>
#include <memory>
#include <variant>
#include "async_primitives.hpp"
#include "StreamTransport.h"
